/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drunkster;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Aleksi
 */
public class frameLisaaDrinkki extends javax.swing.JFrame {

    JFrame main = new JFrame();
    

    
    DB db = new DB();
    
    List<Aines> ainesList = new ArrayList<Aines>();
    List<Drinkki> drinkkiList = new ArrayList<Drinkki>();
    List<Drinkki> kaikkiDrinkit = new ArrayList<Drinkki>();
    
   

    public frameLisaaDrinkki(JFrame main, DrunksterUI UI) {

        this.main = main;
        initComponents(); 
         
    }
    
    
    public void setDrinkkiList(List<Drinkki> drinkkiList){
        this.drinkkiList = drinkkiList;
        cbPoistaDrinkki.removeAllItems();
        
        
        
        try{
            for (Drinkki drinkki : this.drinkkiList){
                String nimi = drinkki.getNimi();      
                cbPoistaDrinkki.addItem(nimi);
                //virhe.setText("höpö");
            }
        }
        catch(Exception ex){
            virhe.setText(ex.toString());
        }
    }
    
    public void setAinesList(List<Aines> ainesList){
        
        this.ainesList = ainesList;
        

        cbAines1.removeAllItems();
        cbAines2.removeAllItems();
        cbAines3.removeAllItems();
        cbAines4.removeAllItems();
        cbAines5.removeAllItems();

        cbAines1.addItem("");
        
         try {
             
            for (Aines aines : this.ainesList) {
                //int id = aines.getId();
                String nimi = aines.getNimi();      
                cbAines1.addItem(nimi);
            }
            for (int i = 0; i < cbAines1.getItemCount();i++){
                cbAines2.addItem(cbAines1.getItemAt(i));
                cbAines3.addItem(cbAines1.getItemAt(i));
                cbAines4.addItem(cbAines1.getItemAt(i));
                cbAines5.addItem(cbAines1.getItemAt(i));
            }
        } catch (Exception ex) {
            Logger.getLogger(DrunksterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaKuvaus = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonPeruuta = new javax.swing.JButton();
        btnlisääDrinkki = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPoistaDrinkki = new javax.swing.JButton();
        cbAines1 = new javax.swing.JComboBox<>();
        cbAines2 = new javax.swing.JComboBox<>();
        cbAines3 = new javax.swing.JComboBox<>();
        cbAines4 = new javax.swing.JComboBox<>();
        cbAines5 = new javax.swing.JComboBox<>();
        virhe = new javax.swing.JLabel();
        textfieldDrinkinNimi = new javax.swing.JTextField();
        labelDrinkinNimi = new javax.swing.JLabel();
        cbPoistaDrinkki = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtareaKuvaus.setColumns(20);
        txtareaKuvaus.setRows(5);
        jScrollPane1.setViewportView(txtareaKuvaus);

        jLabel1.setText("Kuvaus:");

        jButtonPeruuta.setText("Peruuta");
        jButtonPeruuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeruutaActionPerformed(evt);
            }
        });

        btnlisääDrinkki.setText("Lisää");
        btnlisääDrinkki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisääDrinkkiActionPerformed(evt);
            }
        });

        jLabel2.setText("Aines 1:");

        jLabel3.setText("Aines 2:");

        jLabel4.setText("Aines 3:");

        jLabel5.setText("Aines 4:");

        jLabel6.setText("Aines 5:");

        btnPoistaDrinkki.setText("Poista");
        btnPoistaDrinkki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoistaDrinkkiActionPerformed(evt);
            }
        });

        cbAines1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAines2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAines3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAines4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAines5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        virhe.setText("debug");

        labelDrinkinNimi.setText("Drinkin nimi:");

        cbPoistaDrinkki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Poista Drinkki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldDrinkinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDrinkinNimi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAines4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAines5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAines3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAines2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAines1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPoistaDrinkki, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnPoistaDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPeruuta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnlisääDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(virhe))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbAines1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbAines2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelDrinkinNimi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldDrinkinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbAines3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbAines4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbAines5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlisääDrinkki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPeruuta)
                    .addComponent(cbPoistaDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoistaDrinkki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(virhe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPeruutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeruutaActionPerformed
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jButtonPeruutaActionPerformed

    private void btnlisääDrinkkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisääDrinkkiActionPerformed
        String nimi = textfieldDrinkinNimi.getText(); 
        String kuvaus = txtareaKuvaus.getText();
        
        String aines1, aines2, aines3, aines4, aines5;

        aines1 = cbAines1.getModel().getSelectedItem().toString();
        aines2 = cbAines2.getModel().getSelectedItem().toString();
        aines3 = cbAines3.getModel().getSelectedItem().toString();
        aines4 = cbAines4.getModel().getSelectedItem().toString();
        aines5 = cbAines5.getModel().getSelectedItem().toString();
        
        int lennimi = nimi.length(); 
        
        if (lennimi > 0 && lennimi < 31){
            if(!aines1.equals("") && !aines2.equals("")){
                if(aines3.equals("")){
                    db.tallennaUusiDrinkki(virhe, nimi, aines1, aines2, kuvaus);
                    try{
                        db.conn.close();
                    } catch (Exception e){
                        virhe.setText(e.toString());
                    }
                    virhe.setText("Käytetään kahta");
                } else if(aines4.equals("")){
                    db.tallennaUusiDrinkki(virhe, nimi, aines1, aines2, aines3, kuvaus);
                    try{
                        db.conn.close();
                    } catch (Exception e){
                        virhe.setText(e.toString());
                    }
                    virhe.setText("Käytetään kolmea");
                } else if(aines5.equals("")){
                    db.tallennaUusiDrinkki(virhe, nimi, aines1, aines2, aines3, aines4, kuvaus);
                    try{
                        db.conn.close();
                    } catch (Exception e){
                        virhe.setText(e.toString());
                    }
                    virhe.setText("Käytetään neljää");
                } else {
                    db.tallennaUusiDrinkki(virhe, nimi, aines1, aines2, aines3, aines4, aines5, kuvaus);
                    try{
                        db.conn.close();
                    } catch (Exception e){
                        virhe.setText(e.toString());
                    }
                    virhe.setText("Käytetään viittä");
                }
            } else {
                virhe.setText("Aines 1 ja 2 pitää olla valittu!");
            }   
        } else virhe.setText("Nimi oltava 1-30 merkin väliltä.");
    }//GEN-LAST:event_btnlisääDrinkkiActionPerformed

    private void btnPoistaDrinkkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoistaDrinkkiActionPerformed
        String nimi = cbPoistaDrinkki.getModel().getSelectedItem().toString();
        db.poistaDrinkki(virhe, nimi);
        setDrinkkiList(db.haeKaikkiDrinkit(virhe));
    }//GEN-LAST:event_btnPoistaDrinkkiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPoistaDrinkki;
    private javax.swing.JButton btnlisääDrinkki;
    private javax.swing.JComboBox<String> cbAines1;
    private javax.swing.JComboBox<String> cbAines2;
    private javax.swing.JComboBox<String> cbAines3;
    private javax.swing.JComboBox<String> cbAines4;
    private javax.swing.JComboBox<String> cbAines5;
    private javax.swing.JComboBox<String> cbPoistaDrinkki;
    private javax.swing.JButton jButtonPeruuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDrinkinNimi;
    private javax.swing.JTextField textfieldDrinkinNimi;
    private javax.swing.JTextArea txtareaKuvaus;
    private javax.swing.JLabel virhe;
    // End of variables declaration//GEN-END:variables
}
